
services:
  # Veritabanı Servisi (PostgreSQL)
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql
    # 2. .env dosyasındaki değişkenleri buraya bağlayın
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5  
    networks:
      - internal_bridge

  # Backend Servisi (Django)
  backend:
    build: ./backend
    networks:
      - internal_bridge 
      - dokploy-network 
    env_file: .env
    volumes:
      - ./backend:/app 
    environment:
      DB_HOST: db
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate &&
             gunicorn the_hive.wsgi:application --bind 0.0.0.0:8000"

  frontend:
    build: ./frontend
    # container_name: react_frontend
    # ports:
    #   - "3001:81" 
    depends_on:
      - backend
    networks:
      - internal_bridge 
      - dokploy-network 

volumes:
  postgres_data: {}

networks:
  dokploy-network:  
    external: true
  internal_bridge:  
    driver: bridge